wiki/encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("edit", views.edit, name="edit"),
    path("<str:title>", views.entry, name="entry"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

import markdown2
import random

from . import util

def index(request):
    try: 
        if request.GET['q']:
            results = [i for i in util.list_entries() if request.GET['q'].lower() in i.lower()]
            return render(request, "encyclopedia/search.html", {
                'results': results,
                "random": random.choice(util.list_entries()),
            })
    except: 
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "random": random.choice(util.list_entries()),
        })



def entry(request, title):
    entry = util.get_entry(title)
    # markdowner = Markdown()
    convertedEntry = markdown2.markdown(entry).strip()
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "entry": convertedEntry,
        "random": random.choice(util.list_entries()),
    })


class NewEntryForm(forms.Form):
    title = forms.CharField(label="title")
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': '3', 'label': 'content', 'style': 'resize:none'}))

def new(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            util.save_entry(form.cleaned_data['title'], form.cleaned_data['content'])
            return HttpResponseRedirect(reverse("encyclopedia:index"))
    
    return render(request, "encyclopedia/new.html", {
        "random": random.choice(util.list_entries()),
        "form": NewEntryForm(),
    })


def edit(request):
    try:
        if request.method == "GET":
            if request.GET['title']:
                form = NewEntryForm({'title': request.GET['title'], 'content': util.get_entry(request.GET['title'])})
                # form.title = request.GET['title']
                # form.content = util.get_entry(request.GET['title'])
                return render(request, "encyclopedia/edit.html", {
                    "title": request.GET['title'],
                    "form": form,
                })

        if request.method == "POST":
            form = NewEntryForm(request.POST)
            if form.is_valid():
                util.save_entry(form.cleaned_data['title'], form.cleaned_data['content'])
                return HttpResponseRedirect(reverse("encyclopedia:index"))

    except:
        return HttpResponseRedirect(reverse("encyclopedia:index"))

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %} -->

{% block title %}
    Edit
{% endblock %}

{% block body %}
<h1>Edit a Wiki entry</h1>
<form action="{% url 'encyclopedia:edit' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
{{ entry | safe }}
<a href="{% url 'encyclopedia:edit' %}?title={{title}}">Edit Markdown</a>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="/">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="/{{ random }}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create
{% endblock %}

{% block body %}
<h1>Create a new Wiki page</h1>
<form action="{% url 'encyclopedia:new' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% if results %}
            {% for result in results %}
                <li><a href="/{{ result }}">{{ result }}</a></li>
            {% endfor %}
        {% else %}
            <li>No matching entries!</li>
        {% endif %}
    </ul>

{% endblock %}